[package]
name = "voicebox"
version = "0.1.0"
authors = ["Branan Riley <me@branan.info>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
itertools = "0.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
tokio-core = "0.1"
